version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - mkdir -p build
  build:
    commands:
      - 	aws cloudformation package \
          --template-file ./cloudformation.yml \
          --s3-bucket cfn-build-objects \
          --s3-prefix pipieline-sample-target \
          --output-template-file build/cloudformation-template.yml \

  post_build:
    commands:
      - 	aws cloudformation deploy \
          --template-file ./build/cloudformation-template.yml \
          --stack-name pipieline-sample-target \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --region ap-northeast-1 \