version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - mkdir -p build
      - make validate
  build:
    commands:
      - make package
  post_build:
    commands:
      - 	aws cloudformation deploy --template-file ./build/cloudformation-template.yml --stack-name $(STACK_NAME) --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND


