version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - mkdir -p build
      - make validate
  build:
    commands:
      - echo "success?"
  post_build:
    commands:
      - echo "success?"


